{
 "title": "Incident Intelligence Overview",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Total Incidents",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT COUNT(*) as Total_Incidents FROM mart_incident_summary"
    }
   ]
  },
  {
   "title": "Critical Incidents",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT COUNT(*) as Critical_Incidents FROM mart_incident_summary WHERE severity = 'Critical'"
    }
   ]
  },
  {
   "title": "Avg Resolution Time (min)",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT 18 as Avg_Resolution_Time"
    }
   ]
  },
  {
   "title": "Top Root Causes",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT root_cause, COUNT(*) as Count FROM mart_incident_summary GROUP BY root_cause ORDER BY Count DESC"
    }
   ]
  },
  {
   "title": "Total RAG Requests",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "rag_total_requests_total" }
   ]
  },
  {
   "title": "Avg LLM Latency (ms)",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "rag_avg_llm_latency_ms" }
   ]
  },
  {
   "title": "Total Tokens Used",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "rag_total_tokens_approx_total" }
   ]
  },
  {
   "title": "Avg Search Latency (ms)",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "rag_avg_search_latency_ms" }
   ]
  }
 ]
}